/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class altermarkive_uploader_Sampler */

#ifndef _Included_altermarkive_uploader_Sampler
#define _Included_altermarkive_uploader_Sampler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     altermarkive_uploader_Sampler
 * Method:    initiate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_altermarkive_uploader_Sampler_initiate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
