/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guardian_Detector */

#ifndef _Included_guardian_Detector
#define _Included_guardian_Detector
#ifdef __cplusplus
extern "C" {
#endif
#undef guardian_Detector_INTERVAL_MS
#define guardian_Detector_INTERVAL_MS 20L
#undef guardian_Detector_DURATION_S
#define guardian_Detector_DURATION_S 10L
#undef guardian_Detector_N
#define guardian_Detector_N 500L
#undef guardian_Detector_OFFSET_X
#define guardian_Detector_OFFSET_X 0L
#undef guardian_Detector_OFFSET_Y
#define guardian_Detector_OFFSET_Y 500L
#undef guardian_Detector_OFFSET_Z
#define guardian_Detector_OFFSET_Z 1000L
#undef guardian_Detector_OFFSET_X_LPF
#define guardian_Detector_OFFSET_X_LPF 1500L
#undef guardian_Detector_OFFSET_Y_LPF
#define guardian_Detector_OFFSET_Y_LPF 2000L
#undef guardian_Detector_OFFSET_Z_LPF
#define guardian_Detector_OFFSET_Z_LPF 2500L
#undef guardian_Detector_OFFSET_X_HPF
#define guardian_Detector_OFFSET_X_HPF 3000L
#undef guardian_Detector_OFFSET_Y_HPF
#define guardian_Detector_OFFSET_Y_HPF 3500L
#undef guardian_Detector_OFFSET_Z_HPF
#define guardian_Detector_OFFSET_Z_HPF 4000L
#undef guardian_Detector_OFFSET_X_D
#define guardian_Detector_OFFSET_X_D 4500L
#undef guardian_Detector_OFFSET_Y_D
#define guardian_Detector_OFFSET_Y_D 5000L
#undef guardian_Detector_OFFSET_Z_D
#define guardian_Detector_OFFSET_Z_D 5500L
#undef guardian_Detector_OFFSET_SV_TOT
#define guardian_Detector_OFFSET_SV_TOT 6000L
#undef guardian_Detector_OFFSET_SV_D
#define guardian_Detector_OFFSET_SV_D 6500L
#undef guardian_Detector_OFFSET_SV_MAXMIN
#define guardian_Detector_OFFSET_SV_MAXMIN 7000L
#undef guardian_Detector_OFFSET_Z_2
#define guardian_Detector_OFFSET_Z_2 7500L
#undef guardian_Detector_OFFSET_FALLING
#define guardian_Detector_OFFSET_FALLING 8000L
#undef guardian_Detector_OFFSET_IMPACT
#define guardian_Detector_OFFSET_IMPACT 8500L
#undef guardian_Detector_OFFSET_LYING
#define guardian_Detector_OFFSET_LYING 9000L
#undef guardian_Detector_SIZE
#define guardian_Detector_SIZE 9500L
#undef guardian_Detector_FALLING_WAIST_SV_TOT
#define guardian_Detector_FALLING_WAIST_SV_TOT 0.6
#undef guardian_Detector_IMPACT_WAIST_SV_TOT
#define guardian_Detector_IMPACT_WAIST_SV_TOT 2.0
#undef guardian_Detector_IMPACT_WAIST_SV_D
#define guardian_Detector_IMPACT_WAIST_SV_D 1.7
#undef guardian_Detector_IMPACT_WAIST_SV_MAXMIN
#define guardian_Detector_IMPACT_WAIST_SV_MAXMIN 2.0
#undef guardian_Detector_IMPACT_WAIST_Z_2
#define guardian_Detector_IMPACT_WAIST_Z_2 1.5
/*
 * Class:     guardian_Detector
 * Method:    initiate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guardian_Detector_initiate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     guardian_Detector
 * Method:    acquire
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guardian_Detector_acquire
  (JNIEnv *, jclass);

/*
 * Class:     guardian_Detector
 * Method:    buffer
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_guardian_Detector_buffer
  (JNIEnv *, jclass);

/*
 * Class:     guardian_Detector
 * Method:    position
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guardian_Detector_position
  (JNIEnv *, jclass);

/*
 * Class:     guardian_Detector
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guardian_Detector_release
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
